# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: snyk-egg
  name: snyk-egg
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: snyk-egg
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: snyk-egg
    spec:
      containers:
      - image: sheseksnyk/egg-carton:latest
        name: snyk-egg
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: docker-socket-mount
          mountPath: /var/run/docker.sock
        - name: docker-config
          readOnly: true
          mountPath: "/root/.docker"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: docker-socket-mount
        hostPath:
          path: /var/run/docker.sock
          type: ""
      - name: docker-config
        secret:
          secretName: eggdockercfg
          items:
          - key: ".dockerconfigjson"
            path: "config.json"
      serviceAccount: snyk-k8s-service-account
      serviceAccountName: snyk-k8s-service-account
