apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyk-kubernetes-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: snyk-kubernetes-operator
  template:
    metadata:
      labels:
        name: snyk-kubernetes-operator
    spec:
      serviceAccountName: snyk-kubernetes-operator
      containers:
        - name: snyk-kubernetes-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "snyk-kubernetes-operator"
