name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure the action to use conventional commit types
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore
            ci
            build
            revert
          # Don't require scopes
          requireScope: false